# Generated by Django 4.0.1 on 2022-02-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_dailyfreeticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfreeticket',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
