# Generated by Django 4.0.1 on 2022-02-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_coupon_couponhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupon', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Limite de 50 characteres.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='desative essa opcao ao inves de deletar o objeto.'),
        ),
    ]
