# Generated by Django 4.0.1 on 2022-02-10 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_coupon_options_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupoms'},
        ),
        migrations.AlterModelOptions(
            name='couponhistory',
            options={'verbose_name': 'resgate de cupon', 'verbose_name_plural': 'historico de cupons'},
        ),
        migrations.AlterModelOptions(
            name='dailyfreeticket',
            options={'verbose_name': 'Ticket diario', 'verbose_name_plural': 'Tickets diarios'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Limite de 50 characteres.', max_length=50, unique=True, verbose_name='codigo'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='desative essa opcao ao inves de deletar o objeto.', verbose_name='ativado'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='prize',
            field=models.IntegerField(verbose_name='Recompensa'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(verbose_name='Valido ate'),
        ),
        migrations.AlterField(
            model_name='couponhistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='app1.account', verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='couponhistory',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='app1.coupon', verbose_name='cupom'),
        ),
        migrations.AlterField(
            model_name='dailyfreeticket',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.account', verbose_name='conta'),
        ),
        migrations.AlterField(
            model_name='dailyfreeticket',
            name='date',
            field=models.DateField(verbose_name='dia do resgate'),
        ),
    ]
