# Generated by Django 4.0.1 on 2022-02-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_coupon_options_alter_couponhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfreeticket',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.account', verbose_name='conta'),
        ),
    ]
