# Generated by Django 4.0.1 on 2022-02-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_math_hand_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='date',
            field=models.DateTimeField(verbose_name='data'),
        ),
    ]
