# Generated by Django 4.0.1 on 2022-02-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_math_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='active_round',
            field=models.IntegerField(verbose_name='round ativo'),
        ),
    ]
