# Generated by Django 4.0.1 on 2022-03-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_math_active_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img_url',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
