# Generated by Django 4.0.1 on 2022-03-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_math_rounds_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='is_over',
            field=models.BooleanField(default=False, verbose_name='partida finalizada'),
        ),
    ]
