# Generated by Django 4.0.1 on 2022-03-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_math_is_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='is_hold',
            field=models.BooleanField(default=False, verbose_name='parou'),
        ),
    ]
